# Generated by Django 5.2.13 on 2026-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fio_genitive',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
