# Generated by Django 5.2.13 on 2026-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('practice_type', models.CharField(choices=[('study', 'Учебная практика'), ('production', 'Производственная практика')], max_length=20)),
                ('file_type', models.CharField(choices=[('docx', 'DOCX'), ('xlsx', 'XLSX')], max_length=10)),
                ('file', models.FileField(upload_to='templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
