# Generated by Django 5.2.13 on 2026-05-04 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('study_group', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=255)),
                ('course', models.PositiveSmallIntegerField()),
                ('education_form', models.CharField(max_length=100)),
                ('practice_type', models.CharField(choices=[('study', 'Учебная практика'), ('production', 'Производственная практика')], max_length=20)),
                ('practice_code', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('supervisor', models.CharField(max_length=255)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('document_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='templates_app.documenttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('practice_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='documents.practicedata')),
            ],
        ),
    ]
