# Generated by Django 5.2.13 on 2026-05-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generateddocument',
            name='file_type',
        ),
    ]
