# Generated by Django 5.2.13 on 2026-05-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_generateddocument_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicedata',
            name='fio_genitive',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
