# Generated by Django 5.2.13 on 2026-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_practicedata_fio_genitive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('table_name', models.CharField(max_length=100)),
                ('row_id', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
